### ISSUE TITLE
Mots en anglais dans la plateforme en français 

### ISSUE THREAD

**Issue by MaudeFJ** [culturecreates/tech-support-tickets#4]
When we navigate the event the bouton clear is in english even if my langage is FR. 
<img width="714" alt="Capture d’écran, le 2023-05-30 à 09 33 16" src="https://github.com/culturecreates/tech-support-tickets/assets/135066077/35273563-2d49-4bae-810f-b14f1f2b0ef8">

**Comment by troughc** [comment]
@AbhishekPAnil The word for Clear in French is: Éffacer 
Please note the accent on the first letter

**Comment by troughc** [comment]
I updated the develop branch with this change @AbhishekPAnil - over to you!

**Comment by troughc** [comment]
@MaudeFJ this issue is now fixed. Thank you for finding it!

**Comment by MaudeFJ** [comment]
I still see sort by 
<img width="720" alt="Capture d’écran, le 2023-08-07 à 14 49 53" src="https://github.com/culturecreates/tech-support-tickets/assets/135066077/7bc0087d-0912-427e-8aac-6a2d45bf38cb">

**Comment by troughc** [comment]
English word needs to be translated to French in the search bar for events. Check other workspaces too.
cc @AbhishekPAnil 

Sort by in french is:

 Trier par

**Comment by troughc** [comment]
Tested: PASSED
